<!-- START of: finna - Recommend/CollectionSideFacets.phtml -->
<?php
    $title = $this->driver->tryMethod('getArchiveType') === 'collection' ? 'Filter Collection' : 'Filter Archive';
    $this->slot('side-facet-caption')->set($title);
?>
<?php $this->baseUriExtra = $this->recommend->getResults()->getParams()->getCollectionId(); ?>
<?=$this->render('Recommend/SideFacets.phtml')?>
<!-- END of: finna - Recommend/CollectionSideFacets.phtml -->
